defaults:
  - _self_
hydra:
  run:  
    dir: ${logdir}

name: robomimic_transport_dsrl_${now:%Y-%m-%d}_${now:%H-%M-%S}_${seed}
logdir: ${log_dir}/robomimic-finetune/${name}/${now:%Y-%m-%d}_${now:%H-%M-%S}_${seed}
base_policy_path: ./dppo/log/robomimic-pretrain/transport/transport_pre_diffusion_mlp_ta8_td100_ddim-100steps_size2048/2025-04-21_08-40-08_47/checkpoint/state_3000.pt
normalization_path: ./dppo/log/robomimic/${env_name}/normalization.npz
dppo_path: ./dppo

algorithm: dsrl_sac

seed: ???
device: cuda:0
use_wandb: True
env_name: transport
log_dir: ./logs
obs_dim: 59
action_dim: 14
cond_steps: 1
act_steps: 8 # action chunk size of base policy
load_offline_data: False
deterministic_eval: False

eval_interval: 8000
num_evals: 200
save_model_interval: 10000
save_replay_buffer: False


env:
  n_envs:  4
  n_eval_envs: 28
  name: ${env_name}
  max_episode_steps: 800
  reset_at_iteration: False
  save_video: False
  best_reward_threshold_for_success: 1 
  reward_offset: 1
  wrappers:
    robomimic_lowdim:
      normalization_path: ${normalization_path}
      low_dim_keys: ['object',
                    'robot0_eef_pos',
                    'robot0_eef_quat',
                    'robot0_gripper_qpos',
                    "robot1_eef_pos",
                    "robot1_eef_quat",
                    "robot1_gripper_qpos"] 
      abs_action: true
    multi_step:
      n_obs_steps: ${cond_steps}
      n_action_steps: ${act_steps}
      max_episode_steps: ${env.max_episode_steps}
      reset_within_step: True

wandb:
  project: dsrl
  run: ${now:%H-%M-%S}_${name}
  group: robomimic-transport

train:
  tau: 0.005 # Target update rate
  actor_lr: 3e-4
  batch_size: 256
  train_freq: 1 # Update model after this many environment steps
  utd: 20 # Number of gradient steps to take per update
  use_layer_norm: True
  layer_size: 128 # Layer size for actor and critic
  num_layers: 3 # Number of layers for actor and critic
  discount: 0.99
  ent_coef: -1
  target_ent: 0.0
  init_rollout_steps: 20001 # Number of rollout steps of standard diffusion policy to collect for replay buffer before training starts
  action_magnitude: 1 # Maximum action magnitude in noise action space
  n_critics: 2 # Number of critic Q networks
  critic_backup_combine_type: min

model:
  _target_: model.diffusion.diffusion_eval.DiffusionEval
  ft_denoising_steps: 0
  predict_epsilon: True
  denoised_clip_value: 1.0
  randn_clip_value: 3
  network_path: ${base_policy_path}
  network:
    _target_: model.diffusion.mlp_diffusion.DiffusionMLP
    time_dim: 32
    mlp_dims: [2048, 2048, 2048]
    residual_style: True
    cond_dim: ${eval:'${obs_dim} * ${cond_steps}'}
    horizon_steps: ${act_steps}
    action_dim: ${action_dim}
  horizon_steps: ${act_steps}
  obs_dim: ${obs_dim}
  action_dim: ${action_dim}
  denoising_steps: 100
  device: ${device}
  use_ddim: True
  ddim_steps: 100
  controllable_noise: True

# DP config
policy:
  _target_: diffusion_policy.policy.diffusion_unet_lowdim_policy.DiffusionUnetLowdimPolicy
  model:
    _target_: diffusion_policy.model.diffusion.conditional_unet1d.ConditionalUnet1D
    input_dim: 20
    local_cond_dim: null
    global_cond_dim: 118
    diffusion_step_embed_dim: 256
    down_dims:
    - 256
    - 512
    - 1024
    kernel_size: 5
    n_groups: 8
    cond_predict_scale: true
  noise_scheduler:
    _target_: diffusers.schedulers.scheduling_ddpm.DDPMScheduler
    num_train_timesteps: 100
    beta_start: 0.0001
    beta_end: 0.02
    beta_schedule: squaredcos_cap_v2
    variance_type: fixed_small
    clip_sample: true
    prediction_type: epsilon
  horizon: 16
  obs_dim: 59
  action_dim: 20
  n_action_steps: 8
  n_obs_steps: 2
  num_inference_steps: 100
  obs_as_local_cond: false
  obs_as_global_cond: true
  pred_action_steps_only: false
  oa_step_convention: true
  checkpoint_path: /home/vyseian/data/low_dim_transport_mh_diffusion_policy_cnn_higher_var_latest.ckpt